# Generated by Django 5.2.5 on 2025-09-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('skills_offered', models.CharField(blank=True, max_length=200, null=True)),
                ('skills_needed', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
