# Generated by Django 5.2.5 on 2025-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_registration_email_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
