# Generated by Django 5.2.5 on 2025-09-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_registration_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='role',
        ),
    ]
