# Generated by Django 5.2.5 on 2025-10-06 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_registration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
