# Generated by Django 5.2.5 on 2025-10-08 04:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_registration_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_sessions', to='user_app.registration')),
                ('participants', models.ManyToManyField(blank=True, related_name='sessions_joined', to='user_app.registration')),
            ],
        ),
    ]
