# Generated by Django 5.2.5 on 2025-10-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
