# Generated by Django 5.2.5 on 2025-10-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_delete_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('learners', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
