# Generated by Django 5.2.5 on 2025-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_follower_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='user_app.post'),
        ),
    ]
